---
title: "Troubleshoot"
output: html_document
date: "2024-03-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
getwd()

# dfA <- read.csv("../../bk_vabl/data/febrl_4_A")
# dfB <- read.csv("../../bk_vabl/data/febrl_4_B")

df1 <- read.csv("../../bk_vabl/data/febrl_4_A.csv") %>%
  arrange(rec_id) %>%
  mutate(rec_id = row_number())

df2 <- read.csv("../../bk_vabl/data/febrl_4_B.csv") %>%
  arrange(rec_id) %>%
  mutate(rec_id = row_number())

df1 <- df1[1:100, ]
df2 <- df2[1:100, ]



n1 <- nrow(df1)
n2 <- nrow(df2)

Z_true <- seq(1:100)
fields <- c(2, 3, 8, 10, 11)
types <- c("lv", "lv","bi", "bi", "bi")
breaks = c(0, .15)

cd <-  BRL::compareRecords(df1, df2, flds = fields, types = types,
                      breaks = breaks)

chain <- BRL::bipartiteGibbs(cd)

cd <- compare_records(df1, df2, fields = fields, types = types,
                      breaks = breaks)

chain <- fabl(hash, S = 100)
results <- estimate_links(chain, hash)
evaluate_links(results$Z_hat, Z_true, n1)


hash <- hash_comparisons(cd, all_patterns = F)
out <- vabl(hash)

out <- svabl(hash)
results <- estimate_links(out, hash)
results$Z_hat
evaluate_links(results$Z_hat, Z_true, n1)

```

